Exception ignored in: <bound method MinionSol.__del__ of <minion.MinionSol object at 0x2af531831ba8>>
Traceback (most recent call last):
  File "/home/pventura/relationaldef/minion.py", line 128, in __del__
    def __del__(self):
KeyboardInterrupt
Spectrum = [3, 2, 1]
DEFINABLE

Final state: 
  Diversity = 15190
    1-diversity = 4
    2-diversity = 128
    3-diversity = 15058
  #Auts = 15513
  #Isos = 84980
  12517894 calls to Minion

 Performance counter stats for 'timeout --signal=SIGINT 45m python3 ../../main.py':

   15798494.489594      task-clock (msec)         #    0.453 CPUs utilized          
        85,152,162      context-switches          #    0.005 M/sec                  
        20,693,918      cpu-migrations            #    0.001 M/sec                  
     5,459,136,200      page-faults               #    0.346 M/sec                  
88,578,258,761,936      cycles                    #    5.607 GHz                    
72,878,661,017,887      instructions              #    0.82  insn per cycle         
15,058,268,641,468      branches                  #  953.146 M/sec                  
   234,823,145,619      branch-misses             #    1.56% of all branches        

   34864.757223723 seconds time elapsed

