Exception ignored in: <bound method MinionSol.__del__ of <minion.MinionSol object at 0x2b826a21aa90>>
Traceback (most recent call last):
  File "/home/pventura/relationaldef/minion.py", line 132, in __del__
    if not self.EOF:
AttributeError: 'MinionSol' object has no attribute 'EOF'
Spectrum = [3, 2, 1]
CANCELLED

State before abort: 
  Diversity = 6008
    1-diversity = 4
    2-diversity = 131
    3-diversity = 5873
  #Auts = 6162
  #Isos = 23208
  1252106 calls to Minion

 Performance counter stats for 'timeout --signal=SIGINT 45m python3 ../../main.py':

    1252943.287745      task-clock (msec)         #    0.464 CPUs utilized          
         8,335,695      context-switches          #    0.007 M/sec                  
         1,988,258      cpu-migrations            #    0.002 M/sec                  
       541,554,247      page-faults               #    0.432 M/sec                  
 6,993,915,753,840      cycles                    #    5.582 GHz                    
 6,030,024,672,325      instructions              #    0.86  insn per cycle         
 1,247,770,752,075      branches                  #  995.872 M/sec                  
    22,704,673,679      branch-misses             #    1.82% of all branches        

    2700.112906029 seconds time elapsed

