Exception ignored in: <bound method Popen.__del__ of <subprocess.Popen object at 0x2b64d8331320>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/subprocess.py", line 723, in __del__
    def __del__(self, _maxsize=sys.maxsize):
KeyboardInterrupt
Spectrum = [3, 2, 1]
DEFINABLE

Final state: 
  Diversity = 9651
    1-diversity = 4
    2-diversity = 104
    3-diversity = 9543
  #Auts = 9928
  #Isos = 180886
  14737597 calls to Minion

 Performance counter stats for 'timeout --signal=SIGINT 45m python3 ../../main.py':

   15784833.498496      task-clock (msec)         #    0.424 CPUs utilized          
       100,097,694      context-switches          #    0.006 M/sec                  
        23,518,713      cpu-migrations            #    0.001 M/sec                  
     6,459,296,893      page-faults               #    0.409 M/sec                  
92,688,810,968,826      cycles                    #    5.872 GHz                    
88,482,367,750,812      instructions              #    0.95  insn per cycle         
18,425,802,058,096      branches                  # 1167.311 M/sec                  
   296,224,575,781      branch-misses             #    1.61% of all branches        

   37198.026350117 seconds time elapsed

