Exception ignored in: <bound method MinionSol.__del__ of <minion.MinionSol object at 0x2afc335132b0>>
Traceback (most recent call last):
  File "/home/pventura/relationaldef/minion.py", line 132, in __del__
    if not self.EOF:
AttributeError: 'MinionSol' object has no attribute 'EOF'
Spectrum = [3, 2, 1]
CANCELLED

State before abort: 
  Diversity = 5657
    1-diversity = 4
    2-diversity = 136
    3-diversity = 5517
  #Auts = 5762
  #Isos = 18068
  703759 calls to Minion

 Performance counter stats for 'timeout --signal=SIGINT 45m python3 ../../main.py':

    1435079.404132      task-clock (msec)         #    0.531 CPUs utilized          
         4,861,312      context-switches          #    0.003 M/sec                  
         1,218,976      cpu-migrations            #    0.849 K/sec                  
       351,537,449      page-faults               #    0.245 M/sec                  
 6,883,917,093,302      cycles                    #    4.797 GHz                    
 7,918,582,908,677      instructions              #    1.15  insn per cycle         
 1,676,729,210,076      branches                  # 1168.388 M/sec                  
    20,540,446,787      branch-misses             #    1.23% of all branches        

    2700.139584149 seconds time elapsed

