Exception ignored in: <bound method MinionSol.__del__ of <minion.MinionSol object at 0x2ac81aff8208>>
Traceback (most recent call last):
  File "/home/pventura/relationaldef/minion.py", line 132, in __del__
    if not self.EOF:
AttributeError: 'MinionSol' object has no attribute 'EOF'
Spectrum = [3, 2]
CANCELLED

State before abort: 
  Diversity = 1646
    1-diversity = 0
    2-diversity = 52
    3-diversity = 1594
  #Auts = 1740
  #Isos = 108588
  1072960 calls to Minion

 Performance counter stats for 'timeout --signal=SIGINT 45m python3 ../../main.py':

    1068808.893193      task-clock (msec)         #    0.396 CPUs utilized          
         7,204,535      context-switches          #    0.007 M/sec                  
         1,705,322      cpu-migrations            #    0.002 M/sec                  
       475,575,610      page-faults               #    0.445 M/sec                  
 6,594,015,073,300      cycles                    #    6.169 GHz                    
 7,590,829,647,025      instructions              #    1.15  insn per cycle         
 1,596,875,297,886      branches                  # 1494.070 M/sec                  
    24,329,755,721      branch-misses             #    1.52% of all branches        

    2700.028755460 seconds time elapsed

