Exception ignored in: <bound method MinionSol.__del__ of <minion.MinionSol object at 0x2b75971150f0>>
Traceback (most recent call last):
  File "/home/pventura/relationaldef/minion.py", line 132, in __del__
    if not self.EOF:
AttributeError: 'MinionSol' object has no attribute 'EOF'
Spectrum = [3, 2, 1]
CANCELLED

State before abort: 
  Diversity = 5532
    1-diversity = 4
    2-diversity = 136
    3-diversity = 5392
  #Auts = 5638
  #Isos = 20246
  996659 calls to Minion

 Performance counter stats for 'timeout --signal=SIGINT 45m python3 ../../main.py':

    1136074.664504      task-clock (msec)         #    0.421 CPUs utilized          
         6,795,049      context-switches          #    0.006 M/sec                  
         1,650,187      cpu-migrations            #    0.001 M/sec                  
       445,765,249      page-faults               #    0.392 M/sec                  
 6,551,261,393,918      cycles                    #    5.767 GHz                    
 6,672,771,010,153      instructions              #    1.02  insn per cycle         
 1,400,653,106,609      branches                  # 1232.888 M/sec                  
    21,805,783,841      branch-misses             #    1.56% of all branches        

    2700.128446460 seconds time elapsed

